using MathNet.Numerics;
using MathNet.Numerics.Interpolation;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Threading;

namespace SDAQFramework.Math
{
    /// <summary>
    /// Polynomial corrector implemented with Math.NET Numerics Polynomial.
    /// </summary>
    public class Polynom : CorrectorBase
    {
        private readonly double[] _coefficients;
        private readonly Polynomial _polynomial;

        public IReadOnlyList<double> Coefficients => Array.AsReadOnly(_coefficients);
        public int Degree => System.Math.Max(0, _coefficients.Length - 1);

        // Default: zero polynomial with autogenerated name.
        public Polynom() : this(string.Empty, new double[] { 0.0 }) { }

        // Construct from name + coefficients array.
        public Polynom(string name, double[] coefficients) : base(name) {
            if (coefficients == null) {
                throw new ArgumentNullException(nameof(coefficients));
            }

            if (coefficients.Length == 0) {
                throw new ArgumentException("At least one coefficient is required.", nameof(coefficients));
            }

            _coefficients = (double[]) coefficients.Clone();
            _polynomial = new Polynomial(_coefficients);
        }

        // Static JSON factory required by ICorrector's static abstract contract.
        override public ICorrector FromJson(string json) {
            if (string.IsNullOrWhiteSpace(json)) {
                throw new ArgumentException("JSON must be provided.", nameof(json));
            }

            var root = JToken.Parse(json);

            string? name = null;
            if (root.Type == JTokenType.Object) {
                var nameToken = root["name"];
                if (nameToken != null && nameToken.Type == JTokenType.String) {
                    name = nameToken.Value<string>();
                }
            }

            var coefficients = ParseCoefficientsFromJToken(root);
            var p = new Polynom(name ?? string.Empty, coefficients);

            // allow optional clip range in the object
            if (root.Type == JTokenType.Object) {
                var obj = (JObject)root;
                if (obj.TryGetValue("clipRange", StringComparison.OrdinalIgnoreCase, out var crToken) && crToken.Type == JTokenType.Array) {
                    var arr = (JArray)crToken;
                    if (arr.Count >= 2) {
                        double min = ParseNumberToken(arr[0]);
                        double max = ParseNumberToken(arr[1]);
                        p.ClipRange = (min, max);
                    }
                }
                else if (obj.TryGetValue("clipMin", StringComparison.OrdinalIgnoreCase, out var minTok) ||
                         obj.TryGetValue("clipMax", StringComparison.OrdinalIgnoreCase, out var maxTok)) {
                    // partial support: must have both to set
                    if (obj.TryGetValue("clipMin", StringComparison.OrdinalIgnoreCase, out var minT) &&
                        obj.TryGetValue("clipMax", StringComparison.OrdinalIgnoreCase, out var maxT)) {
                        double min = ParseNumberToken(minT);
                        double max = ParseNumberToken(maxT);
                        p.ClipRange = (min, max);
                    }
                }
            }

            return p;
        }

        private static double[] ParseCoefficientsFromJToken(JToken root) {
            if (root.Type == JTokenType.Array) {
                return ReadArray((JArray) root);
            }

            if (root.Type == JTokenType.Object) {
                var coeffsProp = root["coefficients"];
                if (coeffsProp != null && coeffsProp.Type == JTokenType.Array) {
                    return ReadArray((JArray) coeffsProp);
                }

                var coeffsProp2 = root["coeffs"];
                if (coeffsProp2 != null && coeffsProp2.Type == JTokenType.Array) {
                    return ReadArray((JArray) coeffsProp2);
                }
            }

            throw new FormatException("Expected JSON array or object with a 'coefficients' (or 'coeffs') array.");
        }

        private static double[] ReadArray(JArray array) {
            var list = new List<double>(array.Count);
            foreach (var item in array) {
                if (item.Type == JTokenType.Float || item.Type == JTokenType.Integer) {
                    list.Add(item.Value<double>());
                    continue;
                }

                if (item.Type == JTokenType.String && double.TryParse(item.Value<string>(), out var v)) {
                    list.Add(v);
                    continue;
                }

                throw new FormatException("All array elements must be numeric (or numeric strings).");
            }

            return list.ToArray();
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        protected override double EvaluateCore(double x) => _polynomial.Evaluate(x);

        // Note: Evaluate(double[]) is inherited from CorrectorBase.
        public override string ToString() => $"{Name} (Id={Id}, Degree={Degree})";
    }
}