<Project Sdk="MSTest.Sdk/3.6.4">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseVSTest>true</UseVSTest>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Libraries\StatePatternFramework\StatePatternFramework.csproj" />
  </ItemGroup>

</Project>
